apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: my-app-pipeline-run
  annotations:
    # This tells PAC when to trigger
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[master]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    params:
      - name: repo-url
        type: string
      - name: revision
        type: string
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          resolver: cluster
          params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        workspaces:
          - name: output
            workspace: source
        params:
          - name: URL
            value: $(params.repo-url)
          - name: REVISION
            value: $(params.revision)
      # DEBUG: Check workspace contents
      - name: debug-workspace
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: list-files
              image: registry.access.redhat.com/ubi8/ubi-minimal:latest
              script: |
                #!/bin/bash
                echo "=== Workspace Contents ==="
                ls -la $(workspaces.source.path)
                echo ""
                echo "=== Looking for Dockerfile ==="
                find $(workspaces.source.path) -name "Dockerfile*" -o -name "dockerfile*"
                echo ""
                echo "=== Current directory ==="
                pwd
      
      - name: build
        runAfter:
          - debug-workspace
        taskRef:
          resolver: cluster
          params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        workspaces:
          - name: source
            workspace: source
        params:
          - name: IMAGE
            value: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/my-app:$(params.revision)"
      
      - name: deploy
        runAfter:
          - build
        taskSpec:
          params:
          - name: image
            type: string
          - name: app-name
            type: string
          steps:
            - name: deploy
              image: quay.io/openshift/origin-cli:latest
              script: |
                #!/bin/bash
                set -e
                
                APP_NAME="$(params.app-name)"
                IMAGE="$(params.image)"
                
                echo "Checking if deployment ${APP_NAME} exists..."
                
                if oc get deployment ${APP_NAME} 2>/dev/null; then
                  echo "Deployment exists - updating image..."
                  oc set image deployment/${APP_NAME} ${APP_NAME}=${IMAGE}
                  oc rollout status deployment/${APP_NAME} --timeout=5m
                else
                  echo "Deployment does not exist - creating new deployment..."
                  
                  # Create deployment
                  oc create deployment ${APP_NAME} --image=${IMAGE}
                  
                  # Expose as a service
                  oc expose deployment ${APP_NAME} --port=8080
                  
                  # Create route
                  oc expose service ${APP_NAME}
                  
                  # Wait for rollout
                  oc rollout status deployment/${APP_NAME} --timeout=5m
                  
                  echo "---"
                  echo "Deployment created successfully!"
                  echo "Access your app at:"
                  oc get route ${APP_NAME} -o jsonpath='http://{.spec.host}'
                  echo ""
                fi
  
  params:
    - name: repo-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: image
      value: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/my-app:$(params.revision)"
    - name: app-name
      value: "my-app"
  
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
